wxapp:
  appid: wx955d8d61806b3390
  appsecret: ccdc310b68b14908fb028acd97f07b31

pagehelp-size: 10

##todo:测试用
mybatis:
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##todo:测试用

spring:
  session:
    store-type: jdbc
    timeout: 3600s
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
  mail:
    host: smtp.qq.com
    username: 3320243347@qq.com
    password: xiiufdyzcvdgcjbc
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl: true
          auth: true
          starttls:
            enable: true
            required: true
    port: 587
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:C://image/
  datasource:
    username: educa
    password: education
    url: jdbc:mysql://39.107.249.209:3306/education?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT


#server:
#  port: 443
#  ssl:
#    key-store: classpath:cert-1540544580228_korme.xyz.pfx
#    key-store-password: r2u36ojl
#    key-store-type: PKCS12

server:
  port: 8080

#pagehelper:
#  reasonable: true
